### ISSUE TITLE
Modify .gitignore for nested Eclipse files

### ISSUE THREAD

**Issue by daveneiman** [ld4l-labs/Vitro#1]
When importing Vitro into Eclipse there are only top-level entries for .classpath, .project, and .settings.
Please change .gitignore to include the following so that nested projects' Eclipse files are also ignored.

/**/.classpath
/**/.project
/**/.settings

**Comment by rjyounes** [comment]
David, I can't find mention of the double slash in the git documentation. What does it mean? Can they all just use /**/? I.e., 

/**/.classpath
/**/.project
/**/.settings

Thanks.
Rebecca

**Comment by daveneiman** [comment]
I think that was the Markdown at work. Now enclosing in Markdown code tags. This will recurse down to all directories.
`
/**/.classpath

/**/.project

/**/.settings
`

**Comment by rjyounes** [comment]
I've made the change to .gitignore, but you will need to remove them from your local repo and then push that change so that they get removed from the remote repo. Otherwise once they're there they won't go away.

Incidentally, I didn't see any of these files below the top-level.
